# Generated by Django 4.0.6 on 2022-07-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('post_point', models.IntegerField()),
                ('is_selcted', models.BooleanField(default=False)),
                ('is_anony', models.BooleanField(default=True)),
                ('show_nickname', models.CharField(max_length=20)),
                ('major_id', models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='Postsapp.majors')),
                ('parents_post_id', models.ForeignKey(db_column='parents_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='parents_post', to='Postsapp.posts')),
            ],
        ),
    ]
