# Generated by Django 4.0.6 on 2022-07-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Postsapp', '0001_initial'),
        ('Usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Usersapp.user'),
        ),
    ]
