# Generated by Django 4.0.3 on 2022-07-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authapp', '0001_initial'),
        ('Postsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major_id',
            field=models.ForeignKey(db_column='major_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='majors_id', to='Postsapp.majors'),
        ),
    ]
