# Generated by Django 4.0.6 on 2022-07-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Postsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('group_id', models.IntegerField()),
                ('nickname', models.CharField(default='', max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('point', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('major_id', models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.CASCADE, related_name='majors_id', to='Postsapp.majors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
